=== blackears/raven/proj/RavenCore/src/com/kitfox/raven/util/help/HelpIndexSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.kitfox.com/schema/HelpIndexSchema"
    xmlns:tns="http://xml.kitfox.com/schema/HelpIndexSchema"
    elementFormDefault="qualified">
    <xsd:complexType name="HelpIndexType">
        <xsd:sequence>
            <xsd:element name="title" type="tns:TitleType"></xsd:element>
            <xsd:element name="header" type="tns:HeaderType"></xsd:element>
            <xsd:element name="outline" type="tns:OutlineType"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="helpIndex" type="tns:HelpIndexType"></xsd:element>
    <xsd:complexType name="TitleType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string"/>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="HeaderType">
        <xsd:attribute name="src" type="xsd:anyURI"/>
    </xsd:complexType>
    <xsd:complexType name="OutlineType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="page" type="tns:PageType"></xsd:element>
            <xsd:element name="subindex" type="tns:SubindexType"></xsd:element>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="PageType">
        <xsd:complexContent>
            <xsd:extension base="tns:OutlineEntryType">
                <xsd:sequence/>
                <xsd:attribute name="src" type="xsd:anyURI"/>
                <xsd:attribute name="title" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="SubindexType">
        <xsd:complexContent>
            <xsd:extension base="tns:OutlineEntryType">
                <xsd:sequence/>
                <xsd:attribute name="src" type="xsd:anyURI"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    <xsd:complexType name="OutlineEntryType"></xsd:complexType>
</xsd:schema>

=== blackears/raven/proj/RavenEditor/doc/manual/tools/helpIndex.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : helpIndex.xml
    Created on : December 16, 2010, 12:51 AM
    Author     : kitfox
    Description:
        Purpose of the document follows.
-->

<helpIndex xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://xml.kitfox.com/schema/HelpIndexSchema'
   xsi:schemaLocation='http://xml.kitfox.com/schema/HelpIndexSchema ../../../RavenUtil/src/com/kitfox/raven/util/help/HelpIndexSchema.xsd'>
    <title>Tools</title>

    <header src=""/>

    <outline>
        <page title="Paint Flood" src="paintFlood.html"/>
        <page title="Paint Layout" src="paintLayout.html"/>
        <page title="Pan" src="pan.html"/>
        <page title="Pen" src="pen.html"/>
        <page title="Pencil Line" src="pencilLine.html"/>
        <page title="Select" src="select.html"/>
        <page title="Stroke Brush" src="strokeBrush.html"/>
        <page title="Sub Select" src="subselect.html"/>
        <page title="Tumble" src="tumble.html"/>
        <page title="Zoom" src="zoom.html"/>
    </outline>
    
</helpIndex>
